spring:
  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/game_db
    username: game_user
    password: game_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false